version: "2.1"
services:
  jobmanager:
    image: flink:latest
    ports:
      - "8081:8081"
    volumes:
      - ./flink-apps:/opt/flink/usrlib
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  taskmanager:
    image: flink:latest
    depends_on:
       - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 3
